import { FFAccount, User, Order, Review, Conversation, Message } from '@/types';

// ========================
// MOCK USERS
// ========================
export const mockUsers: User[] = [
  {
    id: 'u1',
    username: 'PlayerGod_FF',
    email: 'playergod@gmail.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PlayerGod',
    role: 'seller',
    level: 'Diamond',
    verified: true,
    joinedAt: '2022-03-15',
    totalSales: 342,
    rating: 4.9,
    reviewCount: 289,
    balance: 12500000,
  },
  {
    id: 'u2',
    username: 'BooyahKing',
    email: 'booyahking@gmail.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BooyahKing',
    role: 'seller',
    level: 'Platinum',
    verified: true,
    joinedAt: '2022-07-20',
    totalSales: 128,
    rating: 4.7,
    reviewCount: 115,
    balance: 4800000,
  },
  {
    id: 'u3',
    username: 'FFHunter99',
    email: 'ffhunter@gmail.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FFHunter',
    role: 'buyer',
    level: 'Silver',
    verified: false,
    joinedAt: '2023-01-10',
    totalSales: 0,
    rating: 0,
    reviewCount: 0,
    balance: 500000,
  },
  {
    id: 'u-me',
    username: 'DemoUser',
    email: 'demo@ffmarket.id',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DemoUser',
    role: 'buyer',
    level: 'Gold',
    verified: true,
    joinedAt: '2023-06-01',
    totalSales: 0,
    rating: 0,
    reviewCount: 0,
    balance: 2500000,
  },
];

export const currentUser: User = mockUsers[3]; // Demo logged-in user

// ========================
// MOCK ACCOUNTS (Products)
// ========================
export const mockAccounts: FFAccount[] = [
  {
    id: 'acc1',
    sellerId: 'u1',
    sellerName: 'PlayerGod_FF',
    sellerRating: 4.9,
    sellerLevel: 'Diamond',
    title: 'Akun FF Sultan — Rank Heroic • 2500+ Skin',
    description: 'Akun Free Fire sultan lengkap! Rank Heroic Season 35, 2500+ collectible skins, Chrono + Alok + Kapella characters. Cocok untuk flexing dan kompetitif. Supply Drop & Skywatcher Bundle Rare. Tinggal main!',
    price: 3500000,
    originalPrice: 4200000,
    images: ['https://picsum.photos/seed/ff-1/600/400', 'https://picsum.photos/seed/ff-1b/600/400'],
    rank: 'Heroic',
    level: 79,
    diamonds: 12500,
    totalSkins: 2543,
    gunSkins: ['Hayabusa AK', 'Groza Elite Pass', 'M1887 Incubator', 'MP40 Fire', 'AWM Gold', 'SCAR Royal'],
    characters: ['Chrono', 'Alok', 'Kapella', 'Skyler', 'Wukong', 'Maro'],
    emotes: 89,
    server: 'Indonesia',
    likes: 453,
    views: 8920,
    status: 'available',
    category: 'ultra',
    createdAt: '2024-03-10T08:00:00Z',
    featured: true,
    verified: true,
  },
  {
    id: 'acc2',
    sellerId: 'u1',
    sellerName: 'PlayerGod_FF',
    sellerRating: 4.9,
    sellerLevel: 'Diamond',
    title: 'Akun FF Grandmaster 🔥 Full Bundle + Alok',
    description: 'Akun Grandmaster permanen, banyak bundle langka, karakter Alok + Chrono, cocok untuk yang ingin langsung kompetitif.',
    price: 1750000,
    originalPrice: 2100000,
    images: ['https://picsum.photos/seed/ff-2/600/400'],
    rank: 'Grandmaster',
    level: 72,
    diamonds: 8200,
    totalSkins: 1200,
    gunSkins: ['M1887 Incubator', 'AK Punk Girl', 'MP40 x2 Elite'],
    characters: ['Alok', 'Chrono', 'Maro', 'Rafael'],
    emotes: 45,
    server: 'Indonesia',
    likes: 287,
    views: 5430,
    status: 'available',
    category: 'premium',
    createdAt: '2024-03-12T10:00:00Z',
    featured: true,
    verified: true,
  },
  {
    id: 'acc3',
    sellerId: 'u2',
    sellerName: 'BooyahKing',
    sellerRating: 4.7,
    sellerLevel: 'Platinum',
    title: 'Akun FF Diamond — Rank Platinum OG Character',
    description: 'Akun diamond rank Platinum, OG character lengkap, weapon collection lumayan besar, akun aktif dan legal.',
    price: 950000,
    images: ['https://picsum.photos/seed/ff-3/600/400'],
    rank: 'Platinum',
    level: 60,
    diamonds: 4500,
    totalSkins: 650,
    gunSkins: ['M1887 Punk', 'SCAR Phantom', 'Groza OB36'],
    characters: ['Alok', 'Kapella', 'Skyler'],
    emotes: 22,
    server: 'Indonesia',
    likes: 134,
    views: 2890,
    status: 'available',
    category: 'mid',
    createdAt: '2024-03-15T12:00:00Z',
    featured: false,
    verified: true,
  },
  {
    id: 'acc4',
    sellerId: 'u2',
    sellerName: 'BooyahKing',
    sellerRating: 4.7,
    sellerLevel: 'Platinum',
    title: 'Akun FF Murah Rank Gold — Starter Pack',
    description: 'Cocok buat pemula yang mau naik rank, sudah ada beberapa skin dan karakter base.',
    price: 300000,
    images: ['https://picsum.photos/seed/ff-4/600/400'],
    rank: 'Gold',
    level: 42,
    diamonds: 1200,
    totalSkins: 120,
    gunSkins: ['Groza Base', 'MP40 Base'],
    characters: ['Alok', 'DJ Alok Lite'],
    emotes: 8,
    server: 'Indonesia',
    likes: 89,
    views: 1240,
    status: 'available',
    category: 'cheap',
    createdAt: '2024-03-18T14:00:00Z',
    featured: false,
    verified: false,
  },
  {
    id: 'acc5',
    sellerId: 'u1',
    sellerName: 'PlayerGod_FF',
    sellerRating: 4.9,
    sellerLevel: 'Diamond',
    title: 'Akun FF Server Global Heroic — Premium Bundles',
    description: 'Akun server Global dengan Rank Heroic, bundle premium era OB20-OB35, incubator skins rare, diamonds besar.',
    price: 4200000,
    images: ['https://picsum.photos/seed/ff-5/600/400'],
    rank: 'Heroic',
    level: 82,
    diamonds: 15000,
    totalSkins: 3200,
    gunSkins: ['M1887 x6 Incubator', 'AK Sultan', 'MP40 Incubator', 'SCAR Gold'],
    characters: ['Chrono', 'Alok', 'Skyler', 'Moco', 'Wukong'],
    emotes: 120,
    server: 'Global',
    likes: 612,
    views: 14200,
    status: 'available',
    category: 'ultra',
    createdAt: '2024-03-20T16:00:00Z',
    featured: true,
    verified: true,
  },
  {
    id: 'acc6',
    sellerId: 'u2',
    sellerName: 'BooyahKing',
    sellerRating: 4.7,
    sellerLevel: 'Platinum',
    title: 'Akun FF Grandmaster — Hunting Set Lengkap',
    description: 'Grandmaster season ini, full hunting set, karakter hunting lengkap Maro & Clu.',
    price: 1200000,
    images: ['https://picsum.photos/seed/ff-6/600/400'],
    rank: 'Grandmaster',
    level: 68,
    diamonds: 6800,
    totalSkins: 890,
    gunSkins: ['M1887 Night Mode', 'AWM Sniper', 'AK Gold'],
    characters: ['Maro', 'Clu', 'Alok'],
    emotes: 31,
    server: 'Indonesia',
    likes: 201,
    views: 4100,
    status: 'available',
    category: 'premium',
    createdAt: '2024-03-22T09:00:00Z',
    featured: false,
    verified: true,
  },
  {
    id: 'acc7',
    sellerId: 'u1',
    sellerName: 'PlayerGod_FF',
    sellerRating: 4.9,
    sellerLevel: 'Diamond',
    title: 'Akun FF Murah 500K — Rank Silver Siap Lanjut',
    description: 'Akun hemat tapi potensial besar, rank Silver aktif season ini. Cocok main santai.',
    price: 500000,
    images: ['https://picsum.photos/seed/ff-7/600/400'],
    rank: 'Silver',
    level: 35,
    diamonds: 2200,
    totalSkins: 200,
    gunSkins: ['MP40 Skin Basic', 'UMP Base'],
    characters: ['Alok Lite', 'Kla'],
    emotes: 10,
    server: 'Indonesia',
    likes: 56,
    views: 980,
    status: 'available',
    category: 'cheap',
    createdAt: '2024-03-23T11:00:00Z',
    featured: false,
    verified: false,
  },
  {
    id: 'acc8',
    sellerId: 'u2',
    sellerName: 'BooyahKing',
    sellerRating: 4.7,
    sellerLevel: 'Platinum',
    title: 'Akun FF Ultra Sultan — Full Incubator + Chrono Max',
    description: 'Akun terlengkap yang pernah ada! Semua incubator items, Chrono Max, 4000+ skins, karakter full equipped.',
    price: 8500000,
    images: ['https://picsum.photos/seed/ff-8/600/400'],
    rank: 'Heroic',
    level: 90,
    diamonds: 25000,
    totalSkins: 4100,
    gunSkins: ['All M1887 Collections', 'All AK Collections', 'All Groza', 'MP40 Full Set'],
    characters: ['Chrono MAX', 'Alok MAX', 'Skyler MAX', 'All Characters'],
    emotes: 195,
    server: 'Indonesia',
    likes: 889,
    views: 22500,
    status: 'available',
    category: 'ultra',
    createdAt: '2024-03-25T08:00:00Z',
    featured: true,
    verified: true,
  },
];

// ========================
// MOCK ORDERS
// ========================
export const mockOrders: Order[] = [
  {
    id: 'ord1',
    accountId: 'acc3',
    accountTitle: 'Akun FF Diamond — Rank Platinum OG Character',
    buyerId: 'u-me',
    sellerId: 'u2',
    price: 950000,
    status: 'completed',
    paymentMethod: 'qris',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T14:00:00Z',
  },
  {
    id: 'ord2',
    accountId: 'acc1',
    accountTitle: 'Akun FF Sultan — Rank Heroic • 2500+ Skin',
    buyerId: 'u-me',
    sellerId: 'u1',
    price: 3500000,
    status: 'escrow_holding',
    paymentMethod: 'gopay',
    escrowReleaseAt: '2024-04-10T10:00:00Z',
    createdAt: '2024-04-01T08:00:00Z',
    updatedAt: '2024-04-01T09:30:00Z',
  },
];

// ========================
// MOCK REVIEWS
// ========================
export const mockReviews: Review[] = [
  {
    id: 'rev1',
    accountId: 'acc1',
    orderId: 'ord-old-1',
    reviewerId: 'u3',
    reviewerName: 'FFHunter99',
    reviewerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FFHunter',
    rating: 5,
    comment: 'Transaksi aman banget! Akun sesuai deskripsi, seller responsif 24 jam. Reccomended seller untuk beli akun FF!',
    createdAt: '2024-02-15T16:00:00Z',
    helpful: 23,
  },
  {
    id: 'rev2',
    accountId: 'acc1',
    orderId: 'ord-old-2',
    reviewerId: 'u2',
    reviewerName: 'BooyahKing',
    reviewerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BooyahKing',
    rating: 5,
    comment: 'Sistem escrow sini ngebantu banget, aman dari takut kena scam. Akun legit, puas!',
    createdAt: '2024-02-20T12:00:00Z',
    helpful: 45,
  },
  {
    id: 'rev3',
    accountId: 'acc2',
    orderId: 'ord-old-3',
    reviewerId: 'u3',
    reviewerName: 'FFHunter99',
    reviewerAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FFHunter',
    rating: 4,
    comment: 'Akun oke, rank sesuai, harga worth it. Cuma respon seller agak lama sedikit, overall happy.',
    createdAt: '2024-03-05T10:00:00Z',
    helpful: 12,
  },
];

// ========================
// MOCK CONVERSATIONS
// ========================
export const mockConversations: Conversation[] = [
  {
    id: 'conv1',
    participants: ['u-me', 'u1'],
    lastMessage: 'Oke kak, saya proses pengiriman data akun sekarang ya',
    lastMessageAt: '2024-04-01T10:30:00Z',
    accountId: 'acc1',
    accountTitle: 'Akun FF Sultan — Rank Heroic',
    unreadCount: 2,
  },
  {
    id: 'conv2',
    participants: ['u-me', 'u2'],
    lastMessage: 'Akun sudah saya kirim via chat ini kak, mohon dicek dulu',
    lastMessageAt: '2024-03-01T15:00:00Z',
    accountId: 'acc3',
    accountTitle: 'Akun FF Diamond — Rank Platinum',
    unreadCount: 0,
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg1',
    conversationId: 'conv1',
    senderId: 'u-me',
    senderName: 'DemoUser',
    content: 'Halo kak, apakah akun FF Sultan masih available?',
    timestamp: '2024-04-01T09:00:00Z',
    read: true,
  },
  {
    id: 'msg2',
    conversationId: 'conv1',
    senderId: 'u1',
    senderName: 'PlayerGod_FF',
    content: 'Halo! Masih available kak, silakan order langsung',
    timestamp: '2024-04-01T09:05:00Z',
    read: true,
  },
  {
    id: 'msg3',
    conversationId: 'conv1',
    senderId: 'u-me',
    senderName: 'DemoUser',
    content: 'Siap kak, sudah saya bayar via GoPay. Mohon akun segera dikirimkan',
    timestamp: '2024-04-01T10:00:00Z',
    read: true,
  },
  {
    id: 'msg4',
    conversationId: 'conv1',
    senderId: 'u1',
    senderName: 'PlayerGod_FF',
    content: 'Pembayaran sudah dikonfirmasi sistem kak! Oke kak, saya proses pengiriman data akun sekarang ya',
    timestamp: '2024-04-01T10:30:00Z',
    read: false,
  },
];

// ========================
// HELPERS
// ========================
export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export const rankColors: Record<string, string> = {
  'Heroic': '#f59e0b',
  'Grandmaster': '#8b5cf6',
  'Platinum': '#06b6d4',
  'Gold': '#f59e0b',
  'Silver': '#94a3b8',
  'Bronze': '#cd7c3a',
};

export const rankGlows: Record<string, string> = {
  'Heroic': 'rgba(245,158,11,0.4)',
  'Grandmaster': 'rgba(139,92,246,0.4)',
  'Platinum': 'rgba(6,182,212,0.4)',
  'Gold': 'rgba(245,158,11,0.4)',
  'Silver': 'rgba(148,163,184,0.4)',
  'Bronze': 'rgba(205,124,58,0.4)',
};

export const orderStatusLabel: Record<string, string> = {
  waiting_payment: 'Menunggu Pembayaran',
  payment_confirmed: 'Pembayaran Dikonfirmasi',
  escrow_holding: 'Dana Ditahan (Escrow)',
  account_delivered: 'Akun Terkirim',
  buyer_confirming: 'Menunggu Konfirmasi Pembeli',
  completed: 'Selesai',
  disputed: 'Sengketa',
  cancelled: 'Dibatalkan',
};

export const orderStatusColor: Record<string, string> = {
  waiting_payment: 'warning',
  payment_confirmed: 'blue',
  escrow_holding: 'purple',
  account_delivered: 'blue',
  buyer_confirming: 'warning',
  completed: 'green',
  disputed: 'red',
  cancelled: 'red',
};
